flask-blog/blog/blueprints/blog.py
from flask import Blueprint, render_template,request ,session, redirect,url_for, flash
from blog.db import get_db
import sqlite3
import datetime
from functools import wraps
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, validators, TextAreaField
from ..forms import PostForm, ReplyPostForm, EditPostForm , EditReplyForm

# define our blueprint
blog_bp = Blueprint('blog', __name__)

def login_required(f):
    @wraps(f)

    
    def check(*args, **kwargs):
        

        if 'username' in session:
            return f(*args, **kwargs)
            
        else:

            return redirect('/login')
            # , next=request.url )
            
    return check


@blog_bp.route('/' , methods = ['GET', 'POST'])
@blog_bp.route('/posts' , methods = ['GET', 'POST'])
@login_required
def index():
    
    add_post_form = PostForm()

    if request.method == "GET":

        # get the DB connection
        db = get_db()

        # retrieve all posts
        posts = db.execute(
            'SELECT p.id, title, body, created, author_id, firstname , lastname, likes, dislikes'
            ' FROM post p JOIN user u ON p.author_id = u.id'
            ' ORDER BY created DESC'
        ).fetchall()

        # render 'blog' blueprint with posts
        # return render_template('blog/index.html', posts = posts )

    else :
        
        if add_post_form.validate_on_submit():

            # read post values from the form
            title = add_post_form.title.data
            body = add_post_form.body.data 

            # read the 'uid' from the session for the current logged in user
            author_id = session['uid']

            # get the DB connection
            db = get_db()
            
            # insert post into database
            try:
                # execute the SQL insert statement
                db.execute("INSERT INTO post (author_id, title, body) VALUES (?, ?,?);", (author_id, title, body))
                
                # commit changes to the database
                db.commit()
                flash('You were successfully Add')
                return redirect('/posts') 

            except sqlite3.Error as er:
                print(f"SQLite error: { (' '.join(er.args)) }")
                return redirect("/404")

        # if the user is not logged in, redirect to '/login' 
        if "uid" not in session:
            return redirect('/login')
        
        # else, render the template
    return render_template("blog/index.html", form = add_post_form , posts = posts)


@blog_bp.route('/myposts')
@login_required
def myposts():
    
    # get the DB connection
    db = get_db()

    # retrieve all posts
    posts = db.execute(f'''select * from post WHERE author_id = {session['uid']}''').fetchall()
    
    # render 'blog' blueprint with posts
    return render_template('blog/myposts.html', posts = posts)



@blog_bp.route('/post/add', methods = ['GET', 'POST'])
@login_required
def add_post():


    post_form = PostForm()

    if post_form.validate_on_submit():
        # read post values from the form
        title = post_form.title.data
        body = post_form.body.data 

        # read the 'uid' from the session for the current logged in user
        author_id = session['uid']

        # get the DB connection
        db = get_db()
        
        # insert post into database
        try:
            # execute the SQL insert statement
            db.execute("INSERT INTO post (author_id, title, body) VALUES (?, ?,?);", (author_id, title, body))
            
            # commit changes to the database
            db.commit()
            flash('You were successfully Add')
            return redirect('/posts') 

        except sqlite3.Error as er:
            print(f"SQLite error: { (' '.join(er.args)) }")
            return redirect("/404")

    # if the user is not logged in, redirect to '/login' 
    if "uid" not in session:
        return redirect('/login')
    
    # else, render the template
    return render_template("blog/add-post.html", form = post_form)


@blog_bp.route('/post/<int:post_id>/delete', methods = ['GET', 'POST'])
@login_required
def delete_post(post_id):

    # get the DB connection
    db = get_db()

    db.execute(f"DELETE FROM post WHERE id = {post_id} ")
    db.commit()

    return redirect(url_for("blog.myposts"))


@blog_bp.route('/post/<int:post_id>/edit', methods = ['GET', 'POST'])
@login_required
def edit_post(post_id):

    edit_post_form = EditPostForm() 

    if request.method == "GET":

        db = get_db()

        current_post = db.execute(f"select * from post WHERE id = {post_id}").fetchone()

        edit_post_form.new_title.data = current_post['title']
        edit_post_form.new_body.data = current_post['body']

    
    if edit_post_form.validate_on_submit():
        # read post values from the form
        new_title = edit_post_form.new_title.data
        new_body = edit_post_form.new_body.data 


        # get the DB connection
        db = get_db()
        
        
        try:
            
            db.execute(f"UPDATE post SET title = '{new_title}', body = '{new_body}' WHERE id = '{post_id}' ")    
            
            # commit changes to the database
            db.commit()
            
            return redirect(url_for("blog.myposts")) 

        except sqlite3.Error as er:
            print(f"SQLite error: { (' '.join(er.args)) }")
            return redirect("/404")

    # if the user is not logged in, redirect to '/login' 
    if "uid" not in session:
        return redirect('/login')
    
    # else, render the template
    return render_template("blog/edit_post.html", form = edit_post_form)


@blog_bp.route('/post/<int:post_id>/add_reply', methods = ['GET', 'POST'])
@login_required
def reply_post(post_id):
    db = get_db()
    reply_form = ReplyPostForm()

    if reply_form.validate_on_submit():

        # read post values from the form
        body = reply_form.body.data 
        author_id = session['uid']

        
        try:
            # execute the SQL insert statement
            db.execute("INSERT INTO reply (post_id,author_id,body) VALUES (?,?,?);", (post_id,author_id,body,))
            
            # commit changes to the database
            db.commit()
            return redirect(url_for('blog.reply_post', post_id = post_id))

        except sqlite3.Error as er:
            print(f"SQLite error: { (' '.join(er.args)) }")
            return redirect("/404")

        
    # Display the reply section
    
    # retrieve post
    mypost = db.execute(f"select * from post WHERE id = {post_id}").fetchone()
    
    # retrieve first and last name from author post
    author_id = mypost['author_id']
    post_author = db.execute(f'''select * from user WHERE id = {author_id}''').fetchone()
    

    #retrieve replies 
    replies = db.execute(f'''select * from reply WHERE post_id = {post_id}''').fetchall()

    
    users = db.execute("select * from user").fetchall()



    #render the template
    return render_template("blog/reply_post.html", mypost = mypost, post_author = post_author, form = reply_form, replies = replies, users = users)


@blog_bp.route('/post/<int:post_id>/delete_reply/<int:reply_id>', methods = ['GET', 'POST'])
@login_required
def delete_reply(post_id,reply_id):

    # get the DB connection
    db = get_db()
        
    # delete from DB
    db.execute(f"DELETE FROM reply WHERE id = {reply_id} ")
    db.commit()


    return redirect(url_for('blog.reply_post', post_id = post_id))


@blog_bp.route('/post/<int:post_id>/edit_reply/<int:reply_id>', methods = ['GET', 'POST'])
@login_required
def edit_reply(post_id,reply_id):

    edit_reply_form = EditReplyForm() 

    if request.method == "GET":

        db = get_db()

        current_reply = db.execute(f"select * from reply WHERE id = {reply_id}").fetchone()

        edit_reply_form.new_body.data = current_reply['body']

    
    if edit_reply_form.validate_on_submit():
        # read post values from the form
        new_body = edit_reply_form.new_body.data 


        # get the DB connection
        db = get_db()
        
        
        try:
            
            db.execute(f"UPDATE reply SET body = '{new_body}' WHERE id = '{reply_id}' ")    
            
            # commit changes to the database
            db.commit()
            
            return redirect(url_for("blog.reply_post" , post_id = post_id)) 

        except sqlite3.Error as er:
            print(f"SQLite error: { (' '.join(er.args)) }")
            return redirect("/404")

    # if the user is not logged in, redirect to '/login' 
    if "uid" not in session:
        return redirect('/login')
    
    # else, render the template
    return render_template("blog/edit_reply.html", form = edit_reply_form)


@blog_bp.route("/post/<int:post_id>/like")
@login_required
def like(post_id):
    .
    db = get_db()

    num_of_likes = db.execute("SELECT likes FROM post WHERE id LIKE ?",(post_id,)).fetchone()
    total_likes = num_of_likes['likes']


    num_of_dislikes = db.execute("SELECT dislikes FROM post WHERE id LIKE ?",(post_id,)).fetchone()
    total_dislikes = num_of_dislikes['dislikes']

    reaction_id = db.execute(f"SELECT * FROM reaction WHERE user_id = {session['uid']} AND post_id = {post_id}").fetchone()

    if reaction_id == None:

        db = get_db()

        total_likes += 1

        db.execute(f"UPDATE post SET likes = {total_likes} WHERE id = {post_id}")

        db.execute(f"INSERT INTO reaction (post_id, user_id, like, dislike) VALUES (?, ?, ?, ?);", (post_id, session['uid'], 1, 0))

        db.commit()

        return redirect(url_for("blog.index")) 

    elif reaction_id['favorite'] == 1 and reaction_id['like'] == None and reaction_id['dislike'] == None :
        

        db = get_db()

        total_likes += 1

        db.execute(f"UPDATE post SET likes = {total_likes} WHERE id = {post_id}")

flask-blog/blog/templates/blog/add-post.html
{% extends 'base.html' %}

<!-- header block -->
{% block header %}
<h1>{% block title %}Add Post{% endblock %}</h1>
{% endblock %}

<!-- content block -->
{% block content %}

<div class="div container">
     
  <form method="POST" class="form-group">
      {{ form.hidden_tag() }}

      {{form.title.label}}
      {{form.title(class_="form-control")}}
      <hr style="height:2px;border-width:0;color:gray;background-color:gray">
      
      {{form.body.label}}
      {{form.body(class_="form-control")}}

      <hr style="height:2px;border-width:0;color:gray;background-color:gray">
      
      <center>  {{form.submit(class_="btn btn-secondary")}}   </center>
      <hr style="height:2px;border-width:0;color:gray;background-color:gray">

  </form> </div>
{% endblock %}

flask-blog/blog/templates/blog/display.html
{% extends 'base.html' %} 

<!-- header block -->
{% block header %}
<h3>{% block title %}Your-Posts{% endblock %}</h3>
{% endblock %}

<!-- content block -->
{% block content %} 

{% for post in posts %}

<center>
<div class="container mt-4">    
<div class="card" style="width: 18rem;">
    <div class="card-body">
      <h2 class="card-title">{{ post['title'] }}</h2>
      <hr style="height:2px;border-width:0;color:gray;background-color:gray">
      <h6 class="card-subtitle mb-2 text-muted">By {{session['firstname'] | title}} {{ session['lastname'] | title}} on <br> {{ post['created'] }}</h6>
      <hr style="height:2px;border-width:0;color:gray;background-color:gray">
      <p class="card-text">{{ post['body'] }}</p>
      <hr style="height:2px;border-width:0;color:gray;background-color:gray">
      <a href="{{url_for('blog.edit_post',id=post['id'])}}" class="card-link" title="Edit"><i class="far fa-edit"></i></a>
      <a href="{{url_for('blog.delete_post',id=post['id'])}}" class="card-link" title="Delete"><i class="far fa-trash-alt"></i></a>
    </div>
  </div>
</div>
<hr style="height:2px;border-width:0;color:gray;background-color:gray">
{% endfor %} 
<br>
<a href="/profile" class="btn btn-secondary " type="button" role="button"> Your Profile </a></center>
{% endblock %}

flask-blog/blog/templates/blog/edit_post.html
{% extends 'base.html' %}

<!-- header block -->
{% block header %}
<h3>{% block title %}Edit Post{% endblock %}</h3>
{% endblock %}

<!-- content block -->
{% block content %}



    <div class="div container">
     
        <form method="POST" class="form-group">
            {{ form.hidden_tag() }}

            {{form.new_title.label}}
            {{form.new_title(class_="form-control")}}
            <hr style="height:2px;border-width:0;color:gray;background-color:gray">
            
            {{form.new_body.label}}
            {{form.new_body(class_="form-control")}}

            <hr style="height:2px;border-width:0;color:gray;background-color:gray">
            <center>  {{form.submit(class_="btn btn-secondary")}}   </center>
            <hr style="height:2px;border-width:0;color:gray;background-color:gray">

        </form>

 
    </div>



{% endblock %}

flask-blog/blog/templates/blog/edit_reply.html
{% extends 'base.html' %}

<!-- header block -->
{% block header %}
<h1>{% block title %}Edit-Reply{% endblock %}</h1>
{% endblock %}

<!-- content block -->
{% block content %}

<div class="div container">
     
  <form method="POST" class="form-group">
      {{ form.hidden_tag() }}

      {{form.new_body.label}}
      {{form.new_body(class_="form-control")}}
      <hr style="height:2px;border-width:0;color:gray;background-color:gray">
      
      <center>  {{form.reply(class_="btn btn-secondary")}}   </center>
      <hr style="height:2px;border-width:0;color:gray;background-color:gray">

  </form> </div>
{% endblock %}

flask-blog/blog/templates/blog/index.html
{% extends 'base.html' %}

<!-- header block -->
{% block header %}
<h1>{% block title %}Posts{% endblock %}</h1>

{% endblock %}

<!-- content block -->
{% block content %}

<!-- Button trigger modal -->


<!-- Modal -->


<div class="div container">

  <form method="POST" class="form-group">
    <div style="height: 20%;">
      {{ form.hidden_tag() }}

      {{form.title.label}}
      {{form.title(class_="form-control")}}

      {{form.body.label}}
      {{form.body(class_="form-control")}}
    </div>
    <center> {{form.submit(class_="btn btn-secondary")}} </center>
    <hr style="height:2px;border-width:0;color:gray;background-color:gray">

  </form>
</div>

{% for post in posts %}
<article class="post">
  <header>
    <div>

      <h1>{{ post['title'] }}</h1>
      {% if session['role'] == 1 or session['role'] == 2 %}
      <a style="margin-left: 90%;" href="{{url_for('blog.edit_post',post_id=post['id'])}}" title="Edit"><i
          class="far fa-edit"></i></a>
      {% endif %}


      <div class="about">
        By {{ post['firstname'] }} {{ post['lastname'] }} on {{ post['created'] }}
      </div>
    </div>
  </header>
  <p class="body">{{ post['body'] }}</p>
  <a href="{{url_for('blog.reply_post', post_id = post['id'] )}}"><i class="fas fa-reply mx-1"></i>Reply</a>
  <a href="{{url_for('blog.like', post_id = post['id'] )}}"><i class="fas fa-heart mt-4 mx-1" title="Like"></i></a>{{
  post['likes'] }}
  <a href="{{url_for('blog.dislike', post_id = post['id'] )}}"><i class="fas fa-heart-broken mx-1"
      title="DisLike"></i></a>{{ post['dislikes'] }}
  <a href="{{url_for('blog.favorite', post_id = post['id'] )}}"><i class="fas fa-star" title="Favorite"></i></a>
</article>
<hr style="height:2px;border-width:0;color:gray;background-color:gray">

{% endfor %}


{% endblock content %}

flask-blog/blog/templates/blog/myposts.html
{% extends 'base.html' %}

<!-- header block -->
{% block header %}
<h3>{% block title %}Your-Posts{% endblock %}</h3>
{% endblock %}

<!-- content block -->
{% block content %}

{% for post in posts %}

<center>
  <div class="container mt-4">
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h2 class="card-title">{{ post['title'] }}</h2>
        <hr style="height:2px;border-width:0;color:gray;background-color:gray">
        <h6 class="card-subtitle mb-2 text-muted">By {{session['firstname'] | title}} {{ session['lastname'] | title}}
          on <br> {{ post['created'] }}</h6>
        <hr style="height:2px;border-width:0;color:gray;background-color:gray">
        <p class="card-text">{{ post['body'] }}</p>
        <hr style="height:2px;border-width:0;color:gray;background-color:gray">
        <a href="{{url_for('blog.edit_post',post_id=post['id'])}}" class="btn btn-secondary" title="Edit"><i
            class="far fa-edit"></i></a>

        <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#exampleModal"><i
            class="far fa-trash-alt"></i></button>
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete Post</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <b> Are you sure you want to delete this post ?</b>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a href="{{url_for('blog.delete_post',post_id=post['id'])}}" type="button" class="btn btn-danger">Yes,
                  delete.</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <hr style="height:2px;border-width:0;color:gray;background-color:gray">
  {% endfor %}
  <br>
  <a href="/profile" class="btn btn-secondary " type="button" role="button"> Your Profile </a>
</center>
{% endblock %}

flask-blog/blog/templates/blog/reply_post.html
{% extends 'base.html' %}

<!-- header block -->
{% block header %}
<h4>{% block title %}Reply-Posts{% endblock %}</h4>
{% endblock %}

<!-- content block -->
{% block content %}



<center>
    <div class="container mt-4">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h2 class="card-title">{{ mypost['title'] }}</h2>
                <hr style="height:2px;border-width:0;color:gray;background-color:gray">
                <h6 class="card-subtitle mb-2 text-muted">By {{post_author['firstname'] | title}} {{
                    post_author['lastname'] |
                    title}} on <br> {{ mypost['created'] }}</h6>                    
                <hr style="height:2px;border-width:0;color:gray;background-color:gray">
                <p class="card-text">{{ mypost['body'] }}</p>
                <hr style="height:2px;border-width:0;color:gray;background-color:gray">

            </div>
        </div>
    </div>
    <hr style="height:2px;border-width:0;color:gray;background-color:gray">

</center>


<div class="div container">
    {% for reply in replies %}
    <div class="card text-dark bg-light mb-3" style="max-width: 60rem;">

        {% for user in users %}
        {% if user['id'] == reply['author_id'] %}

        <div class="card-header"><b>{{user['username']}}</b><i> at :
                {{reply['created']}} </i>   
        </div>

        <div class="card-body">
            <p class="card-text">{{ reply['body'] }}</p>
            <hr style="height:2px;border-width:0;color:gray;background-color:#808080">
            <a href="{{url_for('blog.edit_reply',post_id = mypost['id'], reply_id = reply['id'])}}" class="card-link" title="Edit"><i class="far fa-edit"></i></a>
            <!-- <a href="{{url_for('blog.delete_reply',post_id = mypost['id'], reply_id = reply['id'])}}" class="card-link" title="Delete"><i class="far fa-trash-alt"></i></a> -->
            <!-- Button trigger modal -->
<a type="button" class="card-link" data-bs-toggle="modal" data-bs-target="#exampleModal"><i class="far fa-trash-alt"></i></a>
  
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Delete Reply</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <b>Are you sure you want to delete this reply ?</b>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <a href="{{url_for('blog.delete_reply',post_id = mypost['id'], reply_id = reply['id'])}}" type="button" class="btn btn-danger">Save changes</a>
        </div>
      </div>
    </div>
  </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
    {% endfor %}

    


</div>

<hr style="height:2px;border-width:0;color:#808080;background-color:gray">

<div class="div container">
    <center>
        <form method="POST" class="form-group">
            {{ form.hidden_tag() }}


            {{form.body.label}}
            
            {{form.body(class_="form-control" , style_="background-color:gray")}}
            <hr style="height:2px;border-width:0;color:gray;background-color:#808080">

            <center> {{form.reply(class_="btn btn-secondary")}} </center>
            <hr style="height:2px;border-width:0;color:gray;background-color:gray">


        </form>
    </center>

</div>


{% endblock %}